// <auto-generated />
namespace Aviato.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201905051825458_test_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
